CREATE TABLE CUSTOMER
(
    ACCOUNT_NUMBER BIGINT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME     VARCHAR(100),
    LAST_NAME      VARCHAR(100),
    FATHER_NAME    VARCHAR(100),
    DOB            DATE,
    AADHAAR_NUMBER VARCHAR(12) UNIQUE,
    PAN_NUMBER     VARCHAR(10) UNIQUE,
    MOBILE_NUMBER  VARCHAR(20) UNIQUE,
    EMAIL          VARCHAR(150),
    ADDRESS        VARCHAR(200),
    CITY           VARCHAR(100),
    STATE          VARCHAR(100),
    ZIPCODE        VARCHAR(10),
    INCOME         VARCHAR(100),
    BALANCE        DECIMAL(15, 2) DEFAULT 0,
    CREATION_DATE DATETIME DEFAULT CURRENT_TIMESTAMP
) AUTO_INCREMENT = 100000000000;


CREATE TABLE LOGIN_INFO
(
    ACCOUNT_NUMBER BIGINT       NOT NULL PRIMARY KEY,
    PASSWORD_HASH  VARCHAR(255) NOT NULL,
    PIN_HASH       VARCHAR(255) NOT NULL,
    CONSTRAINT FK_CUSTOMER_ACCOUNT
        FOREIGN KEY (ACCOUNT_NUMBER)
            REFERENCES CUSTOMER (ACCOUNT_NUMBER)
            ON DELETE CASCADE
            ON UPDATE CASCADE
) ENGINE = InnoDB;

CREATE TABLE TRANSACTION
(
    TRANSACTION_ID   BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DATE_TIME        DATETIME DEFAULT CURRENT_TIMESTAMP,
    ACCOUNT_NUMBER   BIGINT             NOT NULL,
    TRANSACTION_TYPE VARCHAR(10)        NOT NULL CHECK ( TRANSACTION_TYPE IN ('CREDIT', 'DEBIT') ),
    DESCRIPTION      VARCHAR(200),
    AMOUNT           DECIMAL(15, 2)     NOT NULL,
    CONSTRAINT FOREIGN KEY (ACCOUNT_NUMBER) REFERENCES CUSTOMER (ACCOUNT_NUMBER)
);

CREATE TRIGGER UPDATE_BALANCE
    AFTER INSERT
    ON TRANSACTION
    FOR EACH ROW
BEGIN
    IF NEW.TRANSACTION_TYPE = 'CREDIT' THEN
        UPDATE CUSTOMER
        SET BALANCE = BALANCE + NEW.AMOUNT
        WHERE ACCOUNT_NUMBER = NEW.ACCOUNT_NUMBER;
    ELSEIF NEW.TRANSACTION_TYPE = 'DEBIT' THEN
        UPDATE CUSTOMER
        SET BALANCE = BALANCE - NEW.AMOUNT
        WHERE ACCOUNT_NUMBER = NEW.ACCOUNT_NUMBER;
    END IF;
END;